//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracker.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeEntry
    {
        public int Id_TimeEntry { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Duration { get; set; }
        public int Task_Id { get; set; }
        public int User_Id { get; set; }
    
        public virtual Tasks Tasks { get; set; }
        public virtual Users Users { get; set; }
    }
}
